# Generated by Django 4.2.7 on 2026-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'verbose_name': 'Đề thi', 'verbose_name_plural': 'Đề thi'},
        ),
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Kết quả thi'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Câu hỏi'},
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_random',
            field=models.BooleanField(default=True, help_text='Random câu hỏi'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='pass_score',
            field=models.PositiveIntegerField(default=50, help_text='Điểm đạt (%)'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='Giây'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
