# Generated by Django 4.2.7 on 2026-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumpost',
            options={'ordering': ['-is_pinned', '-created_at'], 'verbose_name': 'Bài đăng diễn đàn'},
        ),
        migrations.AlterModelOptions(
            name='forumreply',
            options={'ordering': ['created_at'], 'verbose_name': 'Trả lời diễn đàn'},
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='forumreply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
